// Everything that is commented out is correct testcode, but because Skills is not supported in packages, they will fail when
//merging with the develop-branch

@isTest
private class HOT_SkillControllerTest {
    //     @isTest
    //     static void getAllSkillsListTest() {
    //         List<Skill> skills = HOT_SkillController.getAllSkillsList();
    //         System.assertEquals(8, skills.size(), 'Could not fetch allSkillsList');
    //     }
}
