@IsTest
private class HOT_AssignedResourceAccessHandlerTest {


	@IsTest
	private static void testAssignedResourceHasAccessToServiceAppointmentAfterInsert() {

		System.assertEquals(null, null);
	}

	@IsTest
	private static void testUserLoseAccessWhenAssignedResourceIsDeleted() {
		System.assertEquals(null, null);
	}

	@IsTest
	private static void testWhenAssignedResourceIsChanged() {
		System.assertEquals(null, null);
	}
}
