public with sharing class HOT_InterestedResourceHandler extends MyTriggers {
    /*public override void onAfterInsert() {

    }

    public override void onAfterUpdate() {
        
    }*/
    
    /* public override void onAfterInsert() {
        List<HOT_Request__c> requestsToGetContactInformationFor = new List<HOT_Request__c>();
        Set<Id> personIdsToUpdate = new Set<Id>();
        for (HOT_Request__c request : (List<HOT_Request__c>) records) {
            // Filter for relevant records to initiate callout to Kontakt og Reservasjonsregisteret (KRR)
            if (request.Person__c != null) {
                personIdsToUpdate.add(request.Person__c);
                requestsToGetContactInformationFor.add(request);
            }
        }*/

}
